import type { Metadata } from "next"
import { Gothic_A1 } from "next/font/google"
import AuthContext from "./context/AuthContext"
import "./globals.css"

const gothic = Gothic_A1({
  weight: ["500", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthContext>
      <html lang="en">
        <body className={gothic.className}>{children}</body>
      </html>
    </AuthContext>
  )
}
